const messages={
 zh:{
  appTitle:'Ordex · 文件编排',saved:'已保存在本机',saving:'正在保存…',saveFailed:'保存失败，请立即导出文件',unnamedProject:'未命名项目',
  selectItem:'选择 {name}',expandCollapse:'展开或收起',insertBefore:'插入到前面',insertAfter:'插入到后面',sameLevel:'同级排序',moveInside:'放入下一级',appendLastChild:'追加为最后一个子项',
  sectionSwapTitle:'拖到另一个一级标交换位置；右键删除',newSection:'新建一级标',trash:'回收站',myProjects:'我的项目',exportTitle:'导出所有一级标及其全部下级文件为 ZIP',exportAll:'导出所有文件',tagline:'把文件，整理成序。',renameSection:'重命名分组',undo:'撤销 ⌘Z',redo:'重做 ⇧⌘Z',importFiles:'导入文件',importFolder:'导入文件夹',newFolder:'新建文件夹',exitSelect:'退出多选',selectMultiple:'多选',selectAll:'全选',selectedCount:'已选 {count} 项',moveUp:'移出到上一层',delete:'删除',tableName:'编号 / 名称',modified:'修改日期',size:'大小',organizer:'文件编排',dropToStart:'拖入文件，开始编排',firstSection:'先创建你的第一个一级标',sectionExamples:'例如：申请材料、项目资料、作品集',appendImport:'导入/拖入文件放到末尾',appendLevel:'作为二级标追加',workspaceCount:'{files} 个文件 · {sections} 个一级标',
  numberingTitle:'打开时隐藏所有可识别的原编号；关闭时恢复完整原始文件名',numberingLabel:'去除原编号',schemeLabel:'编号模式',schemeTitle:'切换编号样式，每一层都可以单独设置',schemePresets:'预设',schemeLevels:'逐层',schemeSeparator:'分隔符',schemeSample:'示例',schemeUpdated:'编号模式已更新',schemeHint:'同级超过 26 个时，字母会继续编成 aa、ab…；超过 3999 个时，罗马数字会改回 1、2、3。注意：导出到本地文件夹后按名称排序，字母与罗马编号可能乱序（例如 v 会排在 ix 前面），需要严格按顺序时请使用数字编号。',scheme_decimal:'数字',scheme_alpha:'字母',scheme_legal:'法律',scheme_roman:'罗马',scheme_chinese:'中文',schemeSepDot:'点 · 1.1',schemeSepDash:'连字符 1-1',schemeSepUnderscore:'下划线 1_1',schemeSepNone:'无 · 11',name:'名称',languageMenu:'选择语言',
  movedToTrash:'已移入回收站，可随时恢复',sectionDeleted:'已删除一级标',moveToTrash:'移入回收站',closeTrash:'关闭回收站',emptyTrash:'一键清空',itemCount:'{count} 项',projectFolder:'项目文件夹',file:'文件',folder:'文件夹',fileCount:'{count} 个文件',originalPosition:'原位置 {number}',containsFiles:'含 {count} 个文件',restore:'恢复',empty:'无内容',projectRestored:'已恢复项目',restoredPosition:'已恢复到原位置 {number}',restoredTo:'已恢复到 {project} · {number}',permanentQuestion:'是否永久删除“{name}”？',cannotUndo:'这会永久删除 Ordex 中该项的记录和导入副本，无法恢复。导入前的原文件及本地项目文件夹不会随之删除；如需删除，请自行在本地处理。',confirmPermanentDelete:'永久删除',no:'否',yes:'是',permanentlyDeleted:'已永久删除“{name}”',deleteFailed:'删除失败，原内容已保留。',emptyQuestion:'确定清空 Ordex 回收站？',emptyCannotUndo:'这会永久删除 Ordex 回收站中的记录和导入副本，无法恢复。电脑上的原文件与项目文件夹仍会保留；如需删除，请自行在本地删除。',confirmEmptyTrash:'清空回收站',trashEmptied:'回收站已清空',emptyFailed:'清空失败，原内容已保留。',
  untitledSection:'未命名分组',folderUnderFileHelp:'文件夹不能成为文件的下一级，请先选择分组或文件夹',maxFive:'最多支持五级编号',numberingHidden:'已隐藏原文件编号',originalNamesRestored:'已恢复原始文件名',newNumber:'松手后编号 {number}',target:'目标 {number}',readFolderFailed:'无法读取文件夹：{error}',createSectionFirst:'请先新建一级标',chooseSectionLocation:'请选择一级标中的位置',folderUnderFile:'文件夹不能成为文件的下一级',importTooDeep:'导入后将超过五级编号，请选择更外层的位置',imported:'已导入 {count} 个文件{removed}',removedCount:'，已移除 {count} 个编号',generatingZip:'正在生成 ZIP…',preparingExport:'正在生成本地导出文件…',exported:'已导出，文件名已包含完整编号',exportFailed:'导出失败：{error}',previewMissing:'找不到这个文件，无法预览',previewFailed:'无法预览：{error}',viewSaveFailed:'界面状态保存失败',renameProject:'重命名 {name}',
  newProject:'新建项目',projectName:'项目名称',enterProjectName:'输入项目名称',cancel:'取消',createOpen:'创建并进入',projectNameRequired:'请填写项目名称',chooseProjectFolder:'请选择用于保存这个项目的本地文件夹',rename:'重命名',moveProjectTrash:'移入回收站 {name}',updated:'最近更新：{date}',noMatchingProjects:'没有匹配的项目',firstProject:'新建你的第一个项目',searchProjects:'搜索项目名称...',search:'搜索',newProjectHelp:'点击右上方“新建项目”，命名后开始编排',openProject:'进入 {name}',projectFolderMissing:'项目文件夹已丢失',projectDataMissing:'项目数据暂不可用',removeMissingProject:'移除项目卡片 {name}',removeMissingQuestion:'移除“{name}”的项目卡片？',removeMissingDetail:'仅移除 Ordex 中的项目记录，不会删除其他本地文件。',removeCard:'移除卡片',missingProjectRemoved:'项目卡片已移除',
  previewClose:'关闭预览',previewPage:'第 {page} / {total} 页',previewSlide:'第 {number} 页',previewEmpty:'此文档没有可显示的内容',previewApproximate:'Office 内容由离线开源组件预览；复杂排版可能与原文件不同。',previewUnsupported:'此格式暂不支持在 Ordex 内预览。',previewOpenOriginal:'用默认应用打开'
 },
 en:{
  appTitle:'Ordex · File Organizer',saved:'Saved locally',saving:'Saving…',saveFailed:'Save failed. Export your files immediately',unnamedProject:'Untitled Project',
  selectItem:'Select {name}',expandCollapse:'Expand or collapse',insertBefore:'Insert before',insertAfter:'Insert after',sameLevel:'Same level',moveInside:'Move inside',appendLastChild:'Append as last child',
  sectionSwapTitle:'Drag onto another top-level section to swap; right-click to delete',newSection:'New Section',trash:'Trash',myProjects:'My Projects',exportTitle:'Export every section and all nested files as a ZIP',exportAll:'Export All Files',tagline:'Put your files in order.',renameSection:'Rename section',undo:'Undo ⌘Z',redo:'Redo ⇧⌘Z',importFiles:'Import Files',importFolder:'Import Folder',newFolder:'New Folder',exitSelect:'Exit Select',selectMultiple:'Select Multiple',selectAll:'Select All',selectedCount:'{count} selected',moveUp:'Move Up One Level',delete:'Delete',tableName:'No. / Name',modified:'Modified',size:'Size',organizer:'File organizer',dropToStart:'Drop files here to start organizing',firstSection:'Create your first section',sectionExamples:'For example: Applications, Project Files, Portfolio',appendImport:'Import or drop files at the end',appendLevel:'Append as level 2',workspaceCount:'{files} files · {sections} sections',
  numberingTitle:'Turn on to remove recognized original numbering from existing and imported filenames; turn off to restore full original filenames',numberingLabel:'Remove Original Numbering',schemeLabel:'Numbering',schemeTitle:'Switch numbering styles, each level can be set separately',schemePresets:'Presets',schemeLevels:'By level',schemeSeparator:'Separator',schemeSample:'Sample',schemeUpdated:'Numbering updated',schemeHint:'Past 26 items in one level, letters continue as aa, ab…; past 3999, roman numerals switch back to 1, 2, 3. Note: sorting exported files by name in the local folder may put letters and roman numerals out of order (v sorts before ix) — use decimal numbering when order matters.',scheme_decimal:'Decimal',scheme_alpha:'Alphabetic',scheme_legal:'Legal',scheme_roman:'Roman',scheme_chinese:'Chinese',schemeSepDot:'Dot · 1.1',schemeSepDash:'Dash 1-1',schemeSepUnderscore:'Underscore 1_1',schemeSepNone:'None · 11',name:'Name',languageMenu:'Choose language',
  movedToTrash:'Moved to Trash. You can restore it anytime',sectionDeleted:'Section deleted',moveToTrash:'Move to Trash',closeTrash:'Close Trash',emptyTrash:'Empty Trash',itemCount:'{count} items',projectFolder:'Project Folder',file:'File',folder:'Folder',fileCount:'{count} files',originalPosition:'Original position {number}',containsFiles:'contains {count} files',restore:'Restore',empty:'Empty',projectRestored:'Project restored',restoredPosition:'Restored to original position {number}',restoredTo:'Restored to {project} · {number}',permanentQuestion:'Permanently delete “{name}”?',cannotUndo:'This permanently deletes the item record and imported copies in Ordex. They cannot be restored. Your original files and local project folder are not deleted; remove them separately from your computer if needed.',confirmPermanentDelete:'Delete Permanently',no:'Cancel',yes:'Delete',permanentlyDeleted:'Permanently deleted “{name}”',deleteFailed:'Delete failed. The original content was kept.',emptyQuestion:'Empty Ordex Trash?',emptyCannotUndo:'This permanently deletes Ordex Trash records and imported copies. They cannot be restored. Your original files and project folders remain on your computer; delete them separately if needed.',confirmEmptyTrash:'Empty Trash',trashEmptied:'Trash emptied',emptyFailed:'Could not empty Trash. The original content was kept.',
  untitledSection:'Untitled Section',folderUnderFileHelp:'A folder cannot be nested under a file. Select a section or folder first',maxFive:'Numbering supports up to five levels',numberingHidden:'Original numbering removed',originalNamesRestored:'Original filenames restored',newNumber:'New number {number}',target:'Target {number}',readFolderFailed:'Could not read folder: {error}',createSectionFirst:'Create a section first',chooseSectionLocation:'Choose a location within a section',folderUnderFile:'A folder cannot be nested under a file',importTooDeep:'The import would exceed five numbering levels. Choose a higher-level location',imported:'Imported {count} files{removed}',removedCount:'; removed numbering from {count}',generatingZip:'Generating ZIP…',preparingExport:'Preparing a local export…',exported:'Exported with complete numbering in every filename',exportFailed:'Export failed: {error}',previewMissing:'File not found. Preview is unavailable',previewFailed:'Unable to preview: {error}',viewSaveFailed:'Interface state save failed',renameProject:'Rename {name}',
  newProject:'New Project',projectName:'Project name',enterProjectName:'Enter project name',cancel:'Cancel',createOpen:'Create and Open',projectNameRequired:'Enter a project name',chooseProjectFolder:'Choose a local folder for this project',rename:'Rename',moveProjectTrash:'Move {name} to Trash',updated:'Updated {date}',noMatchingProjects:'No matching projects',firstProject:'Create your first project',searchProjects:'Search projects...',search:'Search',newProjectHelp:'Click “New Project” above, name it, and start organizing',openProject:'Open {name}',projectFolderMissing:'Project folder is missing',projectDataMissing:'Project data is unavailable',removeMissingProject:'Remove project card {name}',removeMissingQuestion:'Remove the project card for “{name}”?',removeMissingDetail:'Only the Ordex project record will be removed. Other local files will not be deleted.',removeCard:'Remove Card',missingProjectRemoved:'Project card removed',
  previewClose:'Close preview',previewPage:'Page {page} / {total}',previewSlide:'Slide {number}',previewEmpty:'Nothing to display in this document',previewApproximate:'Office content is previewed offline with open-source components; complex layouts may differ from the original.',previewUnsupported:'This format cannot be previewed inside Ordex yet.',previewOpenOriginal:'Open in Default App'
 }
};

export const normalizeLocale=value=>value==='en'?'en':'zh';
export function translate(locale,key,values={}){const template=messages[normalizeLocale(locale)][key]??messages.zh[key]??key;return template.replace(/\{(\w+)\}/g,(_,name)=>String(values[name]??''));}

const errors={
 '只能交换两个一级标':'Only two top-level sections can be swapped','找不到回收项目':'The recycled item could not be found','请先恢复所在的文件夹或一级标':'Restore its parent folder or section first','原位置的层级已改变，请先将原位置移回较外层再恢复':'The original hierarchy changed. Move the parent outward before restoring','找不到这个项目':'The item could not be found','不能移入自身或自己的下级':'An item cannot be moved into itself or its children','一级标请在一级标之间排序':'Top-level sections can only be reordered with other sections','文件需要放在一级标下':'Files must stay under a section','文件夹不能成为文件的下一级':'A folder cannot be nested under a file','最多支持五级编号，子项也不能超过五级':'Numbering supports up to five levels, including children','已经在最外层':'Already at the outermost level','已经是二级标，不能继续移出':'Already at level 2 and cannot be moved farther out','项目名称不能用作本地文件夹名称':'The project name cannot be used as a local folder name','同一位置已有同名 Ordex 项目':'An Ordex project with the same name already exists here','同一位置已有同名且非空的文件夹':'A non-empty folder with the same name already exists here','找不到项目的本地文件夹':'The local project folder could not be found','项目文件夹已恢复，不能移除':'The project folder has returned and cannot be removed','找不到项目':'Project not found','无效文件标识':'Invalid file identifier','项目索引数据不完整':'The project index is incomplete','无效存储类型':'Invalid storage type','工作区数据不完整':'The workspace data is incomplete'
};
export function translateError(locale,message){if(normalizeLocale(locale)==='zh')return message;const text=String(message||'');if(errors[text])return errors[text];if(text.startsWith('文件内容缺失：'))return 'File content is missing: '+text.slice(7);return text;}
