import {test} from 'node:test';
import assert from 'node:assert/strict';
import {makeNode as n,locate,move,moveOut,exportEntries} from './model.js';
test('文件从 1.1 移出，追加为 1.4',()=>{const f=n('a.pdf','file'),folder=n('资料','folder',{children:[f]}),root=n('材料','section',{children:[folder,n('b','file'),n('c','file')]}),tree=[root];moveOut(tree,f.id);assert.equal(locate(tree,f.id).path.join('.'),'1.4');assert.equal(folder.children.length,0);});
test('插入前面，整个分支随位置重新编号',()=>{const a=n('a','folder',{children:[n('child','file')]}),b=n('b','file'),tree=[n('root','section',{children:[a,b]})];move(tree,b.id,a.id,'before');assert.equal(locate(tree,b.id).path.join('.'),'1.1');assert.equal(locate(tree,a.children[0].id).path.join('.'),'1.2.1');});
test('禁止文件夹进入文件、循环移动及第六级',()=>{const file=n('f','file'),folder=n('d','folder'),root=n('r','section',{children:[file,folder]}),tree=[root];assert.throws(()=>move(tree,folder.id,file.id),/文件夹/);folder.children=[n('d2','folder')];assert.throws(()=>move(tree,folder.id,folder.children[0].id),/自身/);file.children=[n('2','file',{children:[n('3','file',{children:[n('4','file')]})]})];const other=n('o','file');root.children.push(other);assert.throws(()=>move(tree,other.id,file.children[0].children[0].children[0].id),/五级/);assert.equal(root.children.length,3);});
test('文件的子文件同目录导出，文件夹保留目录',()=>{const tree=[n('材料','section',{children:[n('说明.pdf','file',{children:[n('附件.pdf','file')]}),n('合同','folder',{children:[n('原件.pdf','file')]})]})];assert.deepEqual(exportEntries(tree).map(x=>x.path),['1 材料/','1 材料/1.1 说明.pdf','1 材料/1.1.1 附件.pdf','1 材料/1.2 合同/','1 材料/1.2 合同/1.2.1 原件.pdf']);});

test('一级标交换后所有下级编号同步变化',async()=>{const {swapSections}=await import('./model.js');const a=n('A','section',{children:[n('a','file')]}),b=n('B','section',{children:[n('b','folder',{children:[n('c','file')]})]});const tree=[a,b];swapSections(tree,a.id,b.id);assert.equal(locate(tree,a.children[0].id).path.join('.'),'2.1');assert.equal(locate(tree,b.children[0].children[0].id).path.join('.'),'1.1.1');});
test('批量删除父子不重复，回收站保留编号，恢复完整分支',async()=>{const {recycle,restoreEntry}=await import('./model.js');const f=n('f','file'),d=n('d','folder',{children:[f]}),r=n('r','section',{children:[d,n('next','file')]}),tree=[r],trash=[];recycle(tree,trash,[d.id,f.id]);assert.equal(trash.length,1);assert.equal(trash[0].number,'1.1');assert.equal(r.children.length,1);assert.equal(restoreEntry(tree,trash,trash[0].id),'1.1');assert.equal(locate(tree,f.id).path.join('.'),'1.1.1');assert.equal(trash.length,0);});
test('恢复需先恢复被删除父级，父级永久缺失则生成恢复分组',async()=>{const {recycle,restoreEntry}=await import('./model.js');const f=n('f','file'),d=n('d','folder',{children:[f]}),r=n('r','section',{children:[d]}),tree=[r],trash=[];recycle(tree,trash,[f.id]);recycle(tree,trash,[d.id]);assert.throws(()=>restoreEntry(tree,trash,trash[0].id),/先恢复/);trash.splice(1,1);const number=restoreEntry(tree,trash,trash[0].id);assert.equal(number,'2.1');assert.equal(tree[1].name,'恢复的文件');});
test('批量删除同级项目保存各自原编号并可逐个恢复',async()=>{const {recycle,restoreEntry}=await import('./model.js');const a=n('a','file'),b=n('b','file'),c=n('c','file'),r=n('r','section',{children:[a,b,c]}),tree=[r],trash=[];recycle(tree,trash,[a.id,b.id]);assert.deepEqual(trash.map(e=>e.number),['1.1','1.2']);restoreEntry(tree,trash,trash[0].id);restoreEntry(tree,trash,trash[0].id);assert.deepEqual(r.children.map(n=>n.id),[a.id,b.id,c.id]);});
test('批量删除同级项目后以任意顺序恢复仍回到原顺序',async()=>{const {recycle,restoreEntry}=await import('./model.js');const a=n('a','file'),b=n('b','file'),c=n('c','file'),r=n('r','section',{children:[a,b,c]}),tree=[r],trash=[];recycle(tree,trash,[a.id,b.id]);restoreEntry(tree,trash,trash.find(e=>e.node.id===b.id).id);restoreEntry(tree,trash,trash.find(e=>e.node.id===a.id).id);assert.deepEqual(r.children.map(n=>n.id),[a.id,b.id,c.id]);});
test('回收站项目可以单独永久删除且不影响其他项目',async()=>{const {recycle,discardTrashEntry}=await import('./model.js');const a=n('a','file'),b=n('b','file'),r=n('r','section',{children:[a,b]}),tree=[r],trash=[];recycle(tree,trash,[a.id,b.id]);assert.equal(discardTrashEntry(trash,trash[0].id).id,a.id);assert.deepEqual(trash.map(entry=>entry.node.id),[b.id]);assert.throws(()=>discardTrashEntry(trash,'missing'),/找不到回收项目/);});
