const fs=require('node:fs');
const path=require('node:path');

class DiskStore{
 constructor(root){this.root=root;fs.mkdirSync(root,{recursive:true});this.recoverPurge();}
 atomicFile(file,data){fs.mkdirSync(path.dirname(file),{recursive:true});const temp=file+'.tmp',fd=fs.openSync(temp,'w',0o600);try{fs.writeFileSync(fd,data);fs.fsyncSync(fd);}finally{fs.closeSync(fd);}fs.renameSync(temp,file);}
 atomic(name,data){this.atomicFile(path.join(this.root,name),data);}
 json(file){return fs.existsSync(file)?JSON.parse(fs.readFileSync(file,'utf8')):null;}
 registry(){return this.json(path.join(this.root,'library.json'))||{cases:[],activeId:null};}
 validId(id){if(typeof id!=='string'||!/^[a-zA-Z0-9-]{1,100}$/.test(id))throw Error('无效文件标识');return id;}
 safeName(name){return String(name||'未命名文件').replace(/[\\/:*?"<>|\x00-\x1f]/g,'_').replace(/[. ]+$/g,'').trim()||'未命名文件';}
 caseMeta(directory){return path.join(path.resolve(directory),'.ordex','case.json');}
 fileIndexPath(directory){return path.join(path.resolve(directory),'.ordex','files.json');}
 fileIndex(directory){return this.json(this.fileIndexPath(directory))||{};}
 liveDirectory(directory){return path.join(path.resolve(directory),'Ordex 文件');}
 trashDirectory(directory){return path.join(path.resolve(directory),'.ordex','trash');}
 prepareCaseDirectory(parentDirectory,name){const caseName=String(name||'').trim(),reserved=/^(con|prn|aux|nul|com[1-9]|lpt[1-9])(\..*)?$/i;if(!caseName||caseName==='.'||caseName==='..'||/[<>:"/\\|?*\x00-\x1f]/.test(caseName)||/[. ]$/.test(caseName)||reserved.test(caseName))throw Error('项目名称不能用作本地文件夹名称');const target=path.join(path.resolve(parentDirectory),caseName);if(fs.existsSync(this.caseMeta(target)))throw Error('同一位置已有同名 Ordex 项目');if(fs.existsSync(target)&&fs.readdirSync(target).length)throw Error('同一位置已有同名且非空的文件夹');fs.mkdirSync(this.liveDirectory(target),{recursive:true});fs.mkdirSync(this.trashDirectory(target),{recursive:true});return target;}
 loadLibrary(){const registry=this.registry();return {activeId:registry.activeId||null,cases:(registry.cases||[]).map(record=>{const missingDirectory=!fs.existsSync(record.directory),saved=missingDirectory?null:this.json(this.caseMeta(record.directory));return saved?{...record,...saved,directory:record.directory,missingDirectory:false}:{...record,workspace:{nodes:[],trash:[],history:[],future:[]},view:{},unavailable:true,missingDirectory};})};}
 saveLibrary(library){if(!Array.isArray(library?.cases))throw Error('项目索引数据不完整');const records=[],knownIds=new Set(this.registry().cases.map(item=>item.id));for(const item of library.cases){if(!item.directory)throw Error(`项目“${item.name}”尚未选择本地文件夹`);const directory=path.resolve(item.directory),workspace=item.workspace||{nodes:[],trash:[],history:[],future:[]};if(fs.existsSync(directory)&&!item.unavailable&&(!knownIds.has(item.id)||fs.existsSync(this.caseMeta(directory)))){fs.mkdirSync(this.liveDirectory(directory),{recursive:true});fs.mkdirSync(this.trashDirectory(directory),{recursive:true});this.syncFiles(directory,workspace);this.atomicFile(this.caseMeta(directory),JSON.stringify({version:1,id:item.id,name:item.name,workspace,view:item.view||{},updatedAt:item.updatedAt,deletedAt:item.deletedAt||null}));}records.push({id:item.id,name:item.name,directory,updatedAt:item.updatedAt,deletedAt:item.deletedAt||null});}this.atomic('library.json',JSON.stringify({version:1,activeId:library.activeId||null,cases:records}));}
 missingCaseIds(){return this.registry().cases.filter(item=>!fs.existsSync(item.directory)).map(item=>item.id);}
 removeMissingCase(id){const registry=this.registry(),item=registry.cases.find(record=>record.id===id);if(!item)throw Error('找不到项目');if(fs.existsSync(item.directory))throw Error('项目文件夹已恢复，不能移除');registry.cases=registry.cases.filter(record=>record.id!==id);if(registry.activeId===id)registry.activeId=null;this.atomic('library.json',JSON.stringify(registry));return this.loadLibrary();}
 read(store,key){if(store==='state'&&key==='case-library')return this.loadLibrary();const name=store==='state'?'workspace.json':store==='view'?'view.json':null;if(!name)throw Error('无效存储类型');return this.json(path.join(this.root,name));}
 write(store,key,value){if(store==='state'&&key==='case-library')return this.saveLibrary(value);const name=store==='state'?'workspace.json':store==='view'?'view.json':null;if(!name)throw Error('无效存储类型');if(store==='state'&&(!Array.isArray(value?.nodes)||!Array.isArray(value?.trash)))throw Error('工作区数据不完整');this.atomic(name,JSON.stringify(value));}
 caseRecord(caseId){const record=this.registry().cases.find(item=>item.id===caseId);if(!record)throw Error('找不到项目的本地文件夹');return record;}
 uniqueName(directory,name,id,index){const safe=this.safeName(name),used=new Set(Object.entries(index).filter(([key])=>key!==id).map(([,value])=>value)),extension=path.extname(safe),stem=extension?safe.slice(0,-extension.length):safe;let candidate=safe,number=2;while(used.has(candidate)){candidate=`${stem} (${number})${extension}`;number++;}return candidate;}
 storedFile(directory,id){this.validId(id);const name=this.fileIndex(directory)[id];if(!name)return null;for(const folder of [this.liveDirectory(directory),this.trashDirectory(directory)]){const file=path.join(folder,name);if(fs.existsSync(file))return file;}return null;}
 writeFile(caseId,id,name,value){const {directory}=this.caseRecord(caseId),index=this.fileIndex(directory),storedName=this.uniqueName(directory,name,this.validId(id),index),file=path.join(this.liveDirectory(directory),storedName);this.atomicFile(file,Buffer.from(value));index[id]=storedName;this.atomicFile(this.fileIndexPath(directory),JSON.stringify(index));return storedName;}
 readFile(caseId,id){const {directory}=this.caseRecord(caseId),file=this.storedFile(directory,id);return file?fs.readFileSync(file):null;}
 previewPath(caseId,id){const {directory}=this.caseRecord(caseId);return this.storedFile(directory,id);}
 desiredFiles(workspace){const desired=new Map(),walk=(items,trashed)=>items.forEach(node=>{if(node.type==='file')desired.set(node.id,{name:node.name,trashed});walk(node.children||[],trashed);});walk(workspace.nodes||[],false);for(const entry of workspace.trash||[])walk([entry.node],true);return desired;}
 syncFiles(directory,workspace){const desired=this.desiredFiles(workspace),index=this.fileIndex(directory),folders=[this.liveDirectory(directory),this.trashDirectory(directory)];for(const [id,target] of desired){const source=this.storedFile(directory,id);if(!source)continue;const storedName=this.uniqueName(directory,target.name,id,index),destination=path.join(target.trashed?folders[1]:folders[0],storedName);if(source!==destination){fs.mkdirSync(path.dirname(destination),{recursive:true});fs.renameSync(source,destination);}index[id]=storedName;}this.atomicFile(this.fileIndexPath(directory),JSON.stringify(index));}
 purge(ids,library){ids.forEach(id=>this.validId(id));this.atomic('purge.json',JSON.stringify({ids,library,directories:this.registry().cases.map(item=>item.directory)}));this.recoverPurge();}
 recoverPurge(){const journal=this.json(path.join(this.root,'purge.json'));if(!journal)return;this.saveLibrary(journal.library);for(const directory of journal.directories||[]){const index=this.fileIndex(directory);for(const id of journal.ids||[]){const file=this.storedFile(directory,id);if(file)fs.rmSync(file,{force:true});delete index[id];}const retained=(journal.library.cases||[]).some(item=>path.resolve(item.directory)===path.resolve(directory));if(retained)this.atomicFile(this.fileIndexPath(directory),JSON.stringify(index));else{fs.rmSync(this.caseMeta(directory),{force:true});fs.rmSync(this.fileIndexPath(directory),{force:true});}}fs.rmSync(path.join(this.root,'purge.json'),{force:true});}
}

module.exports={DiskStore};
